export const xeTableData1 = [
  {
    id: 19,
    createdAt: '2025-07-11 18:35:39',
    updatedAt: '2025-07-11 18:35:39',
    navname: '其他',
    url: null,
    icon: null,
    pid: 0,
    sort: null,
    remark: null,
    tableName: null,
    status: null,
    type: null,
    appId: null,
    appCode: null,
    enable: null,
    children: [
      {
        id: 20,
        createdAt: '2025-07-11 18:36:13',
        updatedAt: '2025-07-11 18:36:13',
        navname: '角色权限关联',
        url: null,
        icon: null,
        pid: 19,
        sort: null,
        remark: null,
        tableName: 'user_roles',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
    ],
    _X_ROW_KEY1: 'row_29',
  },
  {
    id: 11,
    createdAt: '2025-07-01 11:30:40',
    updatedAt: '2025-07-01 11:30:40',
    navname: '项目管理',
    url: null,
    icon: null,
    pid: 0,
    sort: null,
    remark: null,
    tableName: null,
    status: null,
    type: null,
    appId: null,
    appCode: null,
    enable: null,
    children: [
      {
        id: 12,
        createdAt: '2025-07-01 11:30:55',
        updatedAt: '2025-07-01 11:30:55',
        navname: '项目列表',
        url: null,
        icon: null,
        pid: 11,
        sort: null,
        remark: null,
        tableName: 'project', //
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
    ],
    _X_ROW_KEY1: 'row_30',
  },
  {
    id: 6,
    createdAt: '2025-07-01 05:49:52',
    updatedAt: '2025-07-01 05:49:52',
    navname: '系统管理',
    url: null,
    icon: null,
    pid: 0,
    sort: null,
    remark: null,
    tableName: null,
    status: null,
    type: null,
    appId: null,
    appCode: null,
    enable: null,
    children: [
      {
        id: 26,
        createdAt: '2025-07-13 11:27:02',
        updatedAt: '2025-07-13 11:27:02',
        navname: '下拉绑定类型',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'DataDictionaryType',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 25,
        createdAt: '2025-07-13 10:59:17',
        updatedAt: '2025-07-13 10:59:17',
        navname: '下拉绑定管理',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'DataDictionary',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 24,
        createdAt: '2025-07-13 04:45:48',
        updatedAt: '2025-07-13 04:45:48',
        navname: '页面列管理',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'columns',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 23,
        createdAt: '2025-07-13 04:44:05',
        updatedAt: '2025-07-13 04:44:05',
        navname: '页面管理',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'entity',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 22,
        createdAt: '2025-07-12 21:01:51',
        updatedAt: '2025-07-12 21:01:51',
        navname: '视图管理',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'tableview',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 21,
        createdAt: '2025-07-12 14:50:22',
        updatedAt: '2025-07-12 14:50:22',
        navname: '角色权限',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'role_permissions',
        status: '0',
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 18,
        createdAt: '2025-07-11 14:52:47',
        updatedAt: '2025-07-11 14:52:47',
        navname: '用户管理',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'users',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 17,
        createdAt: '2025-07-10 17:24:26',
        updatedAt: '2025-07-10 17:24:26',
        navname: '系统提示管理',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'notification',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 16,
        createdAt: '2025-07-10 03:54:27',
        updatedAt: '2025-07-10 03:54:27',
        navname: '角色管理',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'roles',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 15,
        createdAt: '2025-07-09 12:36:12',
        updatedAt: '2025-07-09 12:36:12',
        navname: '系统定时管理',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'scheduler',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 14,
        createdAt: '2025-07-06 05:32:56',
        updatedAt: '2025-07-06 05:32:56',
        navname: '系统参数类型',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'paramtype',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 13,
        createdAt: '2025-07-06 05:32:37',
        updatedAt: '2025-07-06 05:32:37',
        navname: '系统参数',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'paramvalue',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 10,
        createdAt: '2025-07-01 05:55:49',
        updatedAt: '2025-07-01 05:55:49',
        navname: '菜单管理',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'navs',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 7,
        createdAt: '2025-07-01 05:50:46',
        updatedAt: '2025-07-01 05:50:46',
        navname: '权限列表',
        url: null,
        icon: null,
        pid: 6,
        sort: null,
        remark: null,
        tableName: 'permissions',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
    ],
    _X_ROW_KEY1: 'row_31',
  },
  {
    id: 3,
    createdAt: '2025-07-01 03:50:54',
    updatedAt: '2025-07-01 03:50:54',
    navname: '资源管理',
    url: null,
    icon: null,
    pid: 0,
    sort: null,
    remark: null,
    tableName: null,
    status: null,
    type: null,
    appId: null,
    appCode: null,
    enable: null,
    children: [
      {
        id: 9,
        createdAt: '2025-07-01 05:53:13',
        updatedAt: '2025-07-01 05:53:13',
        navname: '日历列表',
        url: null,
        icon: null,
        pid: 3,
        sort: null,
        remark: null,
        tableName: 'calendar',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 5,
        createdAt: '2025-07-01 05:48:02',
        updatedAt: '2025-07-01 05:48:02',
        navname: '资源列表',
        url: null,
        icon: null,
        pid: 3,
        sort: null,
        remark: null,
        tableName: 'resource',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 4,
        createdAt: '2025-07-01 03:51:25',
        updatedAt: '2025-07-01 03:51:25',
        navname: '用户列表',
        url: null,
        icon: null,
        pid: 3,
        sort: null,
        remark: null,
        tableName: 'users',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
    ],
    _X_ROW_KEY1: 'row_32',
  },
  {
    id: 1,
    createdAt: '2025-07-01 03:07:46',
    updatedAt: '2025-07-01 03:07:46',
    navname: '任务管理',
    url: null,
    icon: null,
    pid: 0,
    sort: null,
    remark: null,
    tableName: 'task',
    status: null,
    type: null,
    appId: null,
    appCode: null,
    enable: null,
    children: [
      {
        id: 8,
        createdAt: '2025-07-01 05:52:46',
        updatedAt: '2025-07-01 05:52:46',
        navname: '里程碑列表',
        url: null,
        icon: null,
        pid: 1,
        sort: null,
        remark: null,
        tableName: 'milestone',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
      {
        id: 2,
        createdAt: '2025-07-01 03:08:30',
        updatedAt: '2025-07-01 03:08:30',
        navname: '任务列表',
        url: null,
        icon: null,
        pid: 1,
        sort: null,
        remark: null,
        tableName: 'task',
        status: null,
        type: null,
        appId: null,
        appCode: null,
        enable: null,
        children: [],
      },
    ],
    _X_ROW_KEY1: 'row_33',
  },
]
// export const xeTableData = new Array(30)
//   .fill(null)
//   .map((row) => {
//     let row1 = JSON.parse(JSON.stringify(xeTableData1))
//     return row1
//   })
//   .flat() //
export const xeTableData = xeTableData1 //
export const xeTableColumns = [
  {
    id: 580,
    tree: 0,
    type: 'integer',
    align: null,
    field: 'id',
    order: 2,
    title: null,
    width: 94,
    frozen: null,
    hidden: 1,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: [],
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 0,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 01:03:47',
    data_type: 'integer',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 01:03:47',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'id',
    editOptions: null,
    fieldFormat: null,
    is_not_null: true,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: true,
    defaultValueType: null,
    ordinal_position: 1,
  },
  {
    id: 581,
    tree: null,
    type: 'timestamp without time zone',
    align: null,
    field: 'createdAt',
    order: null,
    title: null,
    width: 100,
    frozen: null,
    hidden: 1,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: null,
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 17:03:47',
    data_type: 'timestamp without time zone',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 17:03:47',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'createdAt',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 2,
  },
  {
    id: 582,
    tree: null,
    type: 'timestamp without time zone',
    align: null,
    field: 'updatedAt',
    order: null,
    title: null,
    width: 99,
    frozen: null,
    hidden: 1,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: null,
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 17:03:47',
    data_type: 'timestamp without time zone',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 17:03:47',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'updatedAt',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 3,
  },
  {
    id: 583,
    tree: 1,
    type: 'string',
    align: null,
    field: 'navname',
    order: 1,
    title: '菜单名称',
    width: 296,
    frozen: null,
    hidden: null,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: [],
    primary: null,
    editType: 'string',
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 09:20:58',
    data_type: 'character varying',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 09:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'navname',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 4,
  },
  {
    id: 584,
    tree: null,
    type: 'character varying',
    align: null,
    field: 'url',
    order: 2,
    title: '路由',
    width: 183,
    frozen: null,
    hidden: 0,
    editType: 'select',
    options: [
      {
        label: 'test',
        value: 'test',
      },
      {
        label: 'test2',
        value: 'test2', //
      },
    ],
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    primary: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 01:20:58',
    data_type: 'character varying',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 01:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'url',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 5,
  },
  {
    id: 585,
    tree: null,
    type: 'character varying',
    align: null,
    field: 'icon',
    order: 5,
    title: '图标',
    width: null,
    frozen: null,
    hidden: 1,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: null,
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 17:20:58',
    data_type: 'character varying',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 17:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'icon',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 6,
  },
  {
    id: 586,
    tree: null,
    type: 'integer',
    align: null,
    field: 'pid',
    order: 6,
    title: '父级ID',
    width: 100,
    frozen: null,
    hidden: null,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: [],
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 09:20:58',
    data_type: 'integer',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 09:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'pid',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 7,
  },
  {
    id: 587,
    tree: null,
    type: 'number',
    align: null,
    field: 'sort',
    order: 3,
    title: null,
    width: null,
    frozen: null,
    hidden: 1,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: [],
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-22 17:20:58',
    data_type: 'integer',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-22 17:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'sort',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 8,
  },
  {
    id: 588,
    tree: null,
    type: 'character varying',
    align: null,
    field: 'remark',
    order: null,
    title: null,
    width: null,
    frozen: null,
    hidden: 1,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: null,
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 17:20:58',
    data_type: 'character varying',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 17:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'remark',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 9,
  },
  {
    id: 589,
    tree: null,
    type: 'character varying',
    align: null,
    field: 'status',
    order: 7,
    title: '是否启用',
    width: null,
    frozen: null,
    hidden: null,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: [],
    primary: null,
    editType: 'boolean',
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 09:20:58',
    data_type: 'character varying',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 09:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'status',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 10,
  },
  {
    id: 590,
    tree: null,
    type: 'character varying',
    align: null,
    field: 'type',
    order: 8,
    title: null,
    width: null,
    frozen: null,
    hidden: 1,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: null,
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 17:20:58',
    data_type: 'character varying',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 17:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'type',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 11,
  },
  {
    id: 591,
    tree: null,
    type: 'character varying',
    align: null,
    field: 'appId',
    order: 9,
    title: null,
    width: 154,
    frozen: null,
    hidden: 1,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: null,
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 17:20:58',
    data_type: 'character varying',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 17:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'appId',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 12,
  },
  {
    id: 592,
    tree: null,
    type: 'character varying',
    align: null,
    field: 'appCode',
    order: 10,
    title: null,
    width: null,
    frozen: null,
    hidden: 1,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: null,
    primary: null,
    editType: null,
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 17:20:58',
    data_type: 'character varying',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 17:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'appCode',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 13,
  },
  {
    id: 593,
    tree: null,
    type: 'character varying',
    align: null,
    field: 'tableName',
    order: 3,
    title: '表名',
    width: 165,
    frozen: null,
    hidden: null,
    unique: null,
    bgColor: null,
    comment: null,
    default: null,
    options: [],
    primary: null,
    editType: 'string',
    formatFn: null,
    nullable: 1,
    required: null,
    validate: null,
    calculate: null,
    createdAt: '2025-05-23 01:20:58',
    data_type: 'character varying',
    serviceId: null,
    tableName: 'navs',
    updatedAt: '2025-05-23 01:20:58',
    table_name: 'navs',
    addDisabled: null,
    column_name: 'tableName',
    editOptions: null,
    fieldFormat: null,
    is_not_null: false,
    defaultValue: null,
    editDisabled: null,
    optionsField: null,
    table_schema: 'public',
    baseinfoConfig: null,
    column_comment: null,
    is_primary_key: false,
    defaultValueType: null,
    ordinal_position: 16,
  },
]
