export const defaultButtons = [
  {
    fn: '',
    label: '新增',
    _index: 'IBSL4aonns_uQQRxqD2NR',
    _shtml: 'add  ^^^',
    children: [],
    _rowState: 'add',
    defaultFn: 'addMainTableRow',
  },
  {
    label: '编辑',
    _index: 'EBcJ3IOhwqpuZPpWbLX_e',
    _shtml: 'add  ^^^',
    children: [],
    _rowState: 'add',
    defaultFn: 'editTableRows',
  },
  {
    label: '查询',
    _index: 'Lpaq18mpadWcRDj2VZJDB',
    _shtml: 'add  ^^^',
    children: [],
    _rowState: 'add',
    defaultFn: 'openSearchDialog',
  },
  {
    fn: '',
    label: '刷新',
    _index: 'rRyviWUsWvk_1WsXZ1xlc',
    children: [],
    _rowState: 'change',
    defaultFn: 'getTableData',
  },
  {
    label: '打印',
    _index: 'zZsGHU4o9y1jYc0ghFQLq',
    children: [],
    _rowState: 'change',
  },
  {
    label: '导入',
    _index: 'PmK5M1ZFcHp_js7pElUo4',
    children: [],
    _rowState: 'change',
  },
  {
    id: 'mgxinD4ZCTk1r7woWEuaB',
    label: '审核',
    children: [],
  },
]
